### PR TITLE
build(frontend): skip frontend tests, require frontend updated by CI only

### PR DESCRIPTION
**Pull request by andrewazores**
Related to #1118

### CODE REVIEW

**Comment by andrewazores** [comment]
@ebaron not sure what the best way to test out this config update is. It won't run on one of our forks by default unless we go enable Mergify for our own accounts, so it seems like it needs to be done here first.

**Review by ebaron — APPROVED** [review]

**Comment by andrewazores** [comment]
Cool: https://github.com/cryostatio/cryostat/pull/1089#pullrequestreview-1147845547

**Comment by ebaron** [comment]
@andrewazores can we backport this? the frontend tests are holding up our downstream builds.

**Comment by andrewazores** [comment]
Sure.

**Pull request merged**
